Repository sonatype-nexus-community/nexus-repository-r, pull requests merged in 2020-03, with the labels that each got.

#120 Permanent Install Documentation Update
  README.md
Labels: review

#121 nexus-cleanup scope should be 'provided' …
  nexus-repository-r/pom.xml
Labels: cla:signed

#123 NEXUS-23275: NXRM 3.22 Support
  pom.xml
Labels: wip
